config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'wikis' => 'wikis#index'

  resources :wikis

  devise_for :users, controllers: {sessions: 'users/sessions'}
  resources(:users, only: [:show]) {
    put '/downgrade' => 'users#downgrade', as: :downgrade
  }

  get 'welcome/index'

  get 'welcome/about'

  root 'wikis#index'

  resources :charges, only: [:new, :create]

  resources :collaborators, only: [:create, :destroy]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user

  validates :user, presence: true

  has_many :collaborators, dependent: :destroy

  def self.visible_to user
    if user && (user.admin? || user.premium?)
      all
    else
      where private: false
    end
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope Wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = 'Wiki was saved successfully.'
      redirect_to @wiki
    else
      flash.now[:alert] = 'There was an error saving the wiki.'
      render :new
    end
  end

  def show
    @wiki = Wiki.friendly.find params[:id]
    authorize @wiki
    @users = User.all
  end

  def edit
    @wiki = Wiki.friendly.find params[:id]
    authorize @wiki
  end

  def update
    @wiki = Wiki.friendly.find params[:id]
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]

    if @wiki.save
      flash[:notice] = 'Wiki was updated successfully.'
      redirect_to @wiki
    else
      flash.now[:alert] = 'There was an error saving the wiki.'
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.friendly.find params[:id]
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = 'There was an error deleting the wiki.'
      render :show
    end
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label(:private, class: 'check_box') do %>
        <%= f.check_box :private %> Private Wiki
      <% end %>
    </div>
  <% end %>

  <%= f.submit :save %>
<% end %>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<%= render 'form' %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<%= @wikis.each do |wiki| %>
  <p>
    <%= link_to wiki.title, wiki %>
  </p>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<%= render 'form' %>

app/views/wikis/show.html.haml
%h1= @wiki.title
%p= raw @markdown.render @wiki.body
= link_to 'Edit', edit_wiki_path(@wiki), class: 'btn btn-success'
= link_to 'Delete Wiki', @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'}

- if @wiki.user == current_user
  %table
    = @users.each do |u|
      %tr
        %td
          = u.email
        %td
          - if collaborator = u.collaborator_for(@wiki)
            = link_to 'Remove collaborator', collaborator_path(collaborator.id), class: 'btn', method: :delete
          - else
            = link_to 'Add collaborator', collaborators_path(user: current_user, wiki: @wiki), class: 'btn', method: :post