config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'wikis' => 'wikis#index'

  resources :wikis

  devise_for :users, controllers: {sessions: 'users/sessions'}
  resources(:users, only: [:show]) {
    put '/downgrade' => 'users#downgrade', as: :downgrade
  }

  get 'welcome/index'

  get 'welcome/about'

  root 'wikis#index'

  resources :charges, only: [:new, :create]

  resources :collaborators, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to 'Home', welcome_index_path %></li>
      <li><%= link_to 'About', welcome_about_path %></li>
      <% if current_user %>
        <li><%= link_to 'Profile', user_path(current_user) %></li>
      <% end %>
    </ul>

    <ul class="hmenu">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>

    <div class="flash">
      <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
      <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>

</body>
</html>